name: Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          bootstrap: vendor/autoload.php
          args: --coverage-text
          version: 10.5
          php_version: "8.1"